---
title: "Nucleotide diversity"
author: "Khrystyna"
date: "2024-03-12"
output: html_document
---

```{r setup, include=FALSE}
#Libs
library(tidyverse)
library(patchwork)
library(zoo)
library(data.table)


```

#Data for thingvalla only for inversion chromosomes
```{r }
#Directory
dir <- '~/Desktop/Comp_UU/REF_SalAlp_UK/Inversions/Nucleotide_diversity/Homo_LBvsSB_Thin_pg'

#Load data 
files <- list.files(dir)


#Colnames
col_names <- c('Chr',	'WinCenter',	'tW',	'tP',	'tF',	'tH',	'tL',	'Tajima', 'fuf', 'fud',	'fayh',	'zeng',	'nSites')


# Read the desired files
thetas_list <- list()

for(file in files) {
  file_content <- read.table(file.path(dir, file), header = F)[,-1]
  colnames(file_content) <- col_names
  # Process the file content as needed
  thetas_list[[file]] <- file_content
}


#Modify names of the data list 
names(thetas_list) <- gsub(".theta.5kb.thetasWindow.gz.pestPG", '', names(thetas_list) )

names(thetas_list)

# Estimate Pi and Watterson’s theta  -------------------------------------------
l.theta <- list()
l.watt <- list()
l.sum <- list()
l.dfs <- list()

for (pop in seq_along(thetas_list)){
  df.theta <- thetas_list[[pop]]
  pop.name <- names(thetas_list[pop])
  l.theta[[pop.name]] <- mean((as.numeric(df.theta$tP) / as.numeric(df.theta$nSites)), na.rm = T)
  l.watt[[pop.name]] <- mean((as.numeric(df.theta$tW) /as.numeric(df.theta$nSites)), na.rm = T)
  l.sum[[pop.name]] <- sum(as.numeric(df.theta$nSites), na.rm = T)
  df.theta$pop <- pop.name
  l.dfs[[pop.name]] <- df.theta
}

length(l.theta) #as the number of populations
length(l.watt)  #as the number of populations

df.x2 <- data.frame(pop = names(l.theta),
                    pairwise.nuc = round(unlist(l.theta), 4), 
                    wattersons.theta = round(unlist(l.watt), 4),
                    number.sites = round(unlist(l.sum), 4))

#write.table(df.x2, "~/Desktop/Comp_UU/REF_SalAlp_UK/Nucleotide_diversity/Output/Thetas_mean_unfolded_nSites.txt", row.names = F, 
#            quote = F, col.names = T, sep = ' ')

mean.theta.nsites <- df.x2
df.theta.nsites <- bind_rows(l.dfs)
names(df.theta.nsites) <- c("Chr", "WinCenter","tW", "tP","tF","tH","tL","Tajima","fuf","fud","fayh","zeng","nSites", "pop")


# cleaner summary ---------------------------------------------------------
#always filter windows > 10 sites
df.theta.nsites$nSites <- as.numeric(df.theta.nsites$nSites)
df.theta.nsites$tP <- as.numeric(df.theta.nsites$tP)
df.theta.nsites$tW <- as.numeric(df.theta.nsites$tW)

# Plot nucleotide diversity-----------------------------------------------------
df.theta.nsites_withPi <- df.theta.nsites
df.theta.nsites_withPi$Pi <-round(df.theta.nsites_withPi$tP/df.theta.nsites_withPi$nSites, 4)
df.theta.nsites_withPi <- df.theta.nsites_withPi[!is.na(df.theta.nsites_withPi$Pi),]


# Plot -------------------------------------------------------------------------
#Use this data 
df.theta.nsites$WinCenter <- as.numeric(df.theta.nsites$WinCenter)
df.theta.nsites$WinCenter_less <- df.theta.nsites$WinCenter/1000000
df.theta.nsites$tP_per_site <- df.theta.nsites$tP/df.theta.nsites$nSites

#Clean data for the nSites , we are interested in nSites > 10
df.theta.nsites_clean <- df.theta.nsites[ df.theta.nsites$nSites > 10, ]



```





#Prepare for boxplot
```{r }
library(ggpubr)

#Combine all chromosomes and plot on one boxplot
df.theta.nsites_clean_boxplot <- 
  df.theta.nsites_clean %>% 
  dplyr::select(Chr, WinCenter_less, tP_per_site, pop)

df.theta.nsites_clean_boxplot <- 
  df.theta.nsites_clean_boxplot %>%
  mutate(
    Inversion = case_when(Chr == 4 & WinCenter_less >= 75.25 & WinCenter_less <= 76.13 ~ 'Inv4',
                               Chr == 5 & WinCenter_less >= 22.30 & WinCenter_less <= 22.75 ~ 'Inv5',
                               Chr == 9 & WinCenter_less >= 61.30 & WinCenter_less <= 62.11 ~ 'Inv9',
                               Chr == 17 & WinCenter_less >= 32.45 & WinCenter_less <= 33.20 ~ 'Inv17'
                               ),
        Group = case_when(
          
          startsWith(pop,'list_homLB') ~ 'Homozygous major (Large benthic)',
           startsWith(pop,'list_homSB') ~ 'Homozygous minor (Small benthic)')
         )

df.theta.nsites_clean_boxplot_inv_only <- df.theta.nsites_clean_boxplot[!is.na(df.theta.nsites_clean_boxplot$Inversion),]

```


#Wilcox test
```{r }
# List of all inversions to test
inversions <- c("Inv4", "Inv5", "Inv9", "Inv17")
data = df.theta.nsites_clean_boxplot_inv_only


# Initialize a data frame to store results
results <- data.frame(
  Inversion = character(),
  Morph1 = character(),
  Morph2 = character(),
  P_Value = numeric(),
  stringsAsFactors = FALSE
)

# Loop through each inversion
for (inv in inversions) {
  
  # Filter data for the two groups for the current inversion
  large_benthic <- data[data$Group == 'Homozygous major (Large benthic)' & data$Inversion == inv,]
  small_pelagic <- data[data$Group == 'Homozygous minor (Small benthic)' & data$Inversion == inv,]
  
  # Perform Wilcoxon test
  test_result <- wilcox.test(large_benthic$tP_per_site, small_pelagic$tP_per_site)
  
  # Append the result to the results data frame
  results <- rbind(results, data.frame(
    Inversion = inv,
    Morph1 = 'Homozygous major (Large benthic)',
    Morph2 = 'Homozygous minor (Small benthic)',
    P_Value = test_result$p.value
  ))
}


```



#Add summary statistics
```{r }
library(dplyr)

summary_inv <- 
  df.theta.nsites_clean_boxplot_inv_only %>%
  group_by(Inversion, pop) %>%
  summarise(mean_pi = round(mean(tP_per_site),4),
            sd_pi = round(sd(tP_per_site),4))


```




#Plot boxplot for Homo groups only
```{r }
# Define your own colors for Group and Inversion
group_colors <- c('Homozygous minor (Small benthic)' =  "#67a9cf", 
                  'Homozygous major (Large benthic)' = "darkred")

inversion_colors <- c("Inv4" = "black", "Inv5" = "black", 
                      'Inv9' = "black", 'Inv17' = "black")

# Assuming chr_levels is your previously defined levels for the x-axis (Chromosome)
chr_levels <- c("4", "5", "9", "17")

# Reorder the Chromosome variable in your dataframe using the previously defined levels
df.theta.nsites_clean_boxplot_inv_only$Chr <- factor(df.theta.nsites_clean_boxplot_inv_only$Chr, levels = chr_levels)


# Plot with custom colors
plt <- ggplot(df.theta.nsites_clean_boxplot_inv_only) +
  geom_boxplot(aes(x = Chr, y = tP_per_site, color = Inversion, 
                   fill = Group), outlier.shape = NA) +
  scale_fill_manual(values = group_colors) +
  scale_color_manual(values = inversion_colors) +
  theme_classic(13) +
  theme(legend.position = 'none') +
  ylim(0, 0.005)+
  labs(x = 'Chromosome', y = "θπ")+
  annotate('text', y = 0.003, x = 1, label="***", size = 5)+
  annotate('text', y = 0.003, x = 2, label="***", size = 5)+
  annotate('text', y = 0.005, x = 3, label="***", size = 5)+
  annotate('text', y = 0.002, x = 4, label="***", size = 5)
#ggsave('~/Desktop/Comp_UU/REF_SalAlp_UK/Inversions/Output/Boxplots_nucl_div_HomoLBvsSB.pdf', plt, width = 10, height= 3)


```



#Data genome-wide (across 6 largest chromosomes to optimise resource use)
```{r }
#Directory
dir <- '~/Desktop/Comp_UU/REF_SalAlp_UK/Inversions/Benthic_nucl_div'

#Load data 
files <- list.files(dir)

# Filter files that start with numbers from 1 to 13 and end with "mlma"
desired_files <- grep("theta.5kb.thetasWindow.gz.pestPG$", files, value = TRUE)
col_names <- c('Chr',	'WinCenter',	'tW',	'tP',	'tF',	'tH',	'tL',	'Tajima', 'fuf',
               'fud',	'fayh',	'zeng',	'nSites')


# Read the desired files
thetas_list <- list()

for(file in desired_files) {
  file_content <- read.table(file.path(dir, file), header = F)[,-1]
  colnames(file_content) <- col_names
  # Process the file content as needed
  thetas_list[[file]] <- file_content
}

#Modify names of the data list 
names(thetas_list) <- gsub(".theta.5kb.thetasWindow.gz.pestPG", '', names(thetas_list) )

# List of prefixes to search for
prefixes <- c( 'maf_ThiLB', 'maf_ThiSB')  # Add more prefixes as needed

# Initialize a new list to store combined data frames
new_data_list <- list()

# Define a function to bind rows of data frames starting with a similar name
for(prefix in prefixes) {
  # Filter data frames starting with the specified prefix
  matching_data_frames <- grep(paste0("^", prefix), names(thetas_list), value = TRUE)
  
  # If there are matching data frames, bind them row-wise
  if (length(matching_data_frames) > 0) {
    combined_data <- do.call(rbind, thetas_list[matching_data_frames])
    new_data_list[[prefix]] <- combined_data
  }
}


# Estimate Pi and Watterson’s theta  -------------------------------------------

l.theta <- list()
l.watt <- list()
l.sum <- list()
l.dfs <- list()

for (pop in seq_along(new_data_list)){
  df.theta <- new_data_list[[pop]]
  pop.name <- names(new_data_list[pop])
  l.theta[[pop.name]] <- mean((as.numeric(df.theta$tP) / as.numeric(df.theta$nSites)), na.rm = T)
  l.watt[[pop.name]] <- mean((as.numeric(df.theta$tW) /as.numeric(df.theta$nSites)), na.rm = T)
  l.sum[[pop.name]] <- sum(as.numeric(df.theta$nSites), na.rm = T)
  df.theta$pop <- pop.name
  l.dfs[[pop.name]] <- df.theta
}

length(l.theta) #as the number of populations
length(l.watt)  #as the number of populations

df.x2 <- data.frame(pop = names(l.theta),
                    pairwise.nuc = round(unlist(l.theta), 4),  
                    wattersons.theta = round(unlist(l.watt), 4),
                    number.sites = round(unlist(l.sum), 4))


mean.theta.nsites <- df.x2
df.theta.nsites <- bind_rows(l.dfs)
names(df.theta.nsites) <- c("Chr", "WinCenter","tW", "tP","tF","tH","tL","Tajima","fuf","fud","fayh","zeng","nSites", "pop")


# cleaner summary ---------------------------------------------------------
#always filter windows > 10 sites
df.theta.nsites$nSites <- as.numeric(df.theta.nsites$nSites)
df.theta.nsites$tP <- as.numeric(df.theta.nsites$tP)
df.theta.nsites$tW <- as.numeric(df.theta.nsites$tW)

clean.summary.thetas <- 
  df.theta.nsites %>% 
  filter(nSites > 10) %>%
  group_by(pop) %>%
  summarise(mean.pi = round(mean(tP / nSites),4),
            sd.pi = round(sd(tP / nSites),4),
            mean.wat = round(mean(tW / nSites),4),
            sd.wat = round(sd(tW / nSites),4)) %>%
  mutate(out.pi = paste0(mean.pi,"±",sd.pi),
         out.wat = paste0(mean.wat,"±",sd.wat),)

#write.csv(clean.summary.thetas, "/Users/khyku851/Desktop/REF_SalSp/Nucleotide_diversity/Output_thetas/clean_theta_folded_perpop.csv")

# Plot nucleotide diversity---------------------------------------

df.theta.nsites_withPi <- df.theta.nsites
df.theta.nsites_withPi$Pi <-round(df.theta.nsites_withPi$tP/df.theta.nsites_withPi$nSites, 4)

df.theta.nsites_withPi <- df.theta.nsites_withPi[!is.na(df.theta.nsites_withPi$Pi),]

#Use this data 
df.theta.nsites$WinCenter <- as.numeric(df.theta.nsites$WinCenter)
df.theta.nsites$WinCenter_less <- df.theta.nsites$WinCenter/1000000

df.theta.nsites$tP_per_site <- df.theta.nsites$tP/df.theta.nsites$nSites

#Clean data for the nSites , we are interested in nSites > 10
df.theta.nsites_clean_genome_wide <- df.theta.nsites[ df.theta.nsites$nSites > 10, ]

#Select and add group names
df.theta.nsites_clean_genome_wide <- df.theta.nsites_clean_genome_wide %>% 
  dplyr::select(Chr, WinCenter_less, tP_per_site, pop)

df.theta.nsites_clean_genome_wide$Inversion <- "Genome-wide"
 
df.theta.nsites_clean_genome_wide <- 
   df.theta.nsites_clean_genome_wide %>% 
   mutate(Group = case_when(pop == 'maf_ThiSB' ~ 'Small benthic',
                      pop == 'maf_ThiLB' ~ 'Large benthic'))
 
 df.theta.nsites_clean_genome_wide$Chr <- 'Genome-wide'

 df.theta.nsites_clean_genome_wide_DB <- df.theta.nsites_clean_genome_wide[df.theta.nsites_clean_genome_wide$Group == "Small benthic",]
 df.theta.nsites_clean_genome_wide_LB <- df.theta.nsites_clean_genome_wide[df.theta.nsites_clean_genome_wide$Group == "Large benthic",]
 

#Check Wilcox test
wilcox.test(df.theta.nsites_clean_genome_wide_benthic$tP_per_site,df.theta.nsites_clean_genome_wide_pelagic$tP_per_site)
 
```


#Combine data for Genome-wide vs Homozyghous groups only
```{r}
#Genome-wide data: df.theta.nsites_clean_genome_wide_benthic
#Homozyghous groups: df.theta.nsites_clean_boxplot_inv_only

df_genome_wide_benthic_vs_homo <- rbind(df.theta.nsites_clean_genome_wide, df.theta.nsites_clean_boxplot_inv_only)


```


#Plot boxplot
```{r }
# Define your own colors for Group and Inversion
group_colors <- c("Small benthic" =  "brown3", "Large benthic" = "darkgreen",
                  'Homozygous minor (Small benthic)' =  "#67a9cf", 
                  'Homozygous major (Large benthic)' = "darkred")

              
inversion_colors <- c("Inv4" = "black", "Inv5" = "black", 
                      'Inv9' = "black", 'Inv17' = "black",
                      'Genome-wide' = "black")

# Assuming chr_levels is your previously defined levels for the x-axis (Chromosome)
chr_levels <- c("Genome-wide", "4", "5", "9", "17")

# Reorder the Chromosome variable in your dataframe using the previously defined levels
df_genome_wide_benthic_vs_homo$Chr <- factor(df_genome_wide_benthic_vs_homo$Chr, levels = chr_levels)


# Plot with custom colors
plt <- ggplot(df_genome_wide_benthic_vs_homo) +
  geom_boxplot(aes(x = Chr, y = tP_per_site, color = Inversion, fill = Group), 
               outlier.shape = NA) +
  scale_fill_manual(values = group_colors) +
  scale_color_manual(values = inversion_colors) +
  theme_classic(18) +
  ylim(0, 0.007)+
  labs(x = 'Scaffold', y = "Pairwise theta")+
  theme(legend.position = 'none') +
  annotate('text', y = 0.003, x = 1, label="***", size = 5)+
  annotate('text', y = 0.003, x = 2, label="***", size = 5)+
  annotate('text', y = 0.003, x = 3, label="**", size = 5)+
  annotate('text', y = 0.0055, x = 4, label="***", size = 5)+
  annotate('text', y = 0.003, x = 5, label="***", size = 5)+

  annotate("text", x = 1, y =  0.005, label = "Large benthivorous", color = "darkgreen", size = 5, fontface = "bold")+
  annotate("text", x = 1, y =  0.0044, label = "Small benthivorous", color = "brown3", size = 5, fontface = "bold")+
  annotate("text", x = 3, y =  0.005, label = "Homozygous small benthivorous", color = "#67a9cf", size = 5,fontface = "bold")+
  annotate("text", x = 3, y =  0.0044, label = "Homozygous large benthivorous", color = "brown4", size = 5, fontface = "bold")+
  annotate("text", x = 3, y =  0.006, label = "Wilcoxon test", color = "black", size = 5, fontface = "bold")+
   annotate("text", x = 0.5, y = 0.007, label = "f",size = 6, hjust = 0, vjust = 1, 
             fontface = "bold")

ggsave('~/Desktop/Comp_UU/REF_SalAlp_UK/Inversions/Output/Boxplots_nucl_div_HOMO_Benthic.pdf', plt, width = 11, height= 3, dpi = 300)
ggsave('~/Desktop/Comp_UU/REF_SalAlp_UK/Inversions/Output/Boxplots_nucl_div_HOMO_Benthic.png', plt, width = 11, height= 3, dpi = 300)

```
